name: Update Rainfall Data

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-rain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Scrape rainfall and update JSON
        run: node .github/scripts/fetch_rain.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add rain_today.json
          git commit -m "Update rain data"
          git push
