name: Update Rainfall Data

on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:

jobs:
  update-rain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Scrape rainfall and update JSON
        run: node .github/scripts/fetch_rain.js

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    
          git add rain_today.json debug_row.txt debug_screenshot.png || true

          git commit -m "Update rain data with debug info" || echo "Nothing to commit"
          git push origin main

